//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitManage.Resources.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InitManage.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        internal static string AllReservations {
            get {
                return ResourceManager.GetString("AllReservations", resourceCulture);
            }
        }
        
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        internal static string BeNotifiedBeforeBooking {
            get {
                return ResourceManager.GetString("BeNotifiedBeforeBooking", resourceCulture);
            }
        }
        
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        internal static string BookThe {
            get {
                return ResourceManager.GetString("BookThe", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string EnterTheAddress {
            get {
                return ResourceManager.GetString("EnterTheAddress", resourceCulture);
            }
        }
        
        internal static string EnterYourSearch {
            get {
                return ResourceManager.GetString("EnterYourSearch", resourceCulture);
            }
        }
        
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string LoadingOptions {
            get {
                return ResourceManager.GetString("LoadingOptions", resourceCulture);
            }
        }
        
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        internal static string LoadingTypes {
            get {
                return ResourceManager.GetString("LoadingTypes", resourceCulture);
            }
        }
        
        internal static string LocalNotificationStatus {
            get {
                return ResourceManager.GetString("LocalNotificationStatus", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginInProgress {
            get {
                return ResourceManager.GetString("LoginInProgress", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NumberOfPlaces {
            get {
                return ResourceManager.GetString("NumberOfPlaces", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Peoples {
            get {
                return ResourceManager.GetString("Peoples", resourceCulture);
            }
        }
        
        internal static string PictureLink {
            get {
                return ResourceManager.GetString("PictureLink", resourceCulture);
            }
        }
        
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        internal static string ReceiveNotificationBeforeBooking {
            get {
                return ResourceManager.GetString("ReceiveNotificationBeforeBooking", resourceCulture);
            }
        }
        
        internal static string SelectOptions {
            get {
                return ResourceManager.GetString("SelectOptions", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        internal static string NoResourceResult {
            get {
                return ResourceManager.GetString("NoResourceResult", resourceCulture);
            }
        }
    }
}
